name: Publish Release to Modrinth

# Minimum Required Secrets:
# - MODRINTH_TOKEN (Modrinth API token with permissions to create versions)
# - MODRINTH_ID (The ID of the Modrinth project to publish to)
# - DISCORD_WEBHOOK_URL (The URL of the Discord webhook to send notifications to)

on:
  release:
    types: [ published ]

env:
  MOD_NAME: Cobblemon PokeTotem
  ARTIFACT_BASENAME: cobblemon-poketotem
  RELEASE_JARS_ARTIFACT_PREFIX: release-jars
  FABRIC_LOADER_VERSION: '0.17.2+'
  NEOFORGE_LOADER_VERSION: '21.1.182+'
  MODRINTH_GAME_VERSION: 1.21.1
  MODRINTH_DEPENDENCIES: |-
    [
      {"project_id":"MdwFAVRL","dependency_type":"required"},
      {"project_id":"j2JrSWnx","dependency_type":"required"},
      {"project_id":"KzjvlKEN","dependency_type":"required"}
    ]
  DISCORD_ICON_URL: "https://raw.githubusercontent.com/Matthiesen-dev/.github/refs/heads/main/mod-logos/cobblemon-poketotem.png"

# The dependencies above correspond to:
# - Cobblemon (MdwFAVRL)
# - Matthiesen Lib API (j2JrSWnx)
# - GooeyLibs (KzjvlKEN)

jobs:
  prepare:
    uses: matthiesen-dev/automation/.github/workflows/prepare-publishing.yml@main
    with:
      tag_name: ${{ github.event.release.tag_name }}
    secrets:
      git_token: ${{ secrets.GITHUB_TOKEN }}

  publish_modrinth:
    needs: prepare
    uses: matthiesen-dev/automation/.github/workflows/publish-modrinth-multiloader.yml@main
    if: ${{ needs.prepare.outputs.is_snapshot == 'false' }}
    with:
      artifact_basename: ${{ env.ARTIFACT_BASENAME }}
      mod_name: ${{ env.MOD_NAME }}
      version: ${{ needs.prepare.outputs.version }}
      changelog: ${{ github.event.release.body }}
      modrinth_game_version: ${{ env.MODRINTH_GAME_VERSION }}
      modrinth_id: ${{ secrets.MODRINTH_ID }}
      modrinth_dependencies: ${{ env.MODRINTH_DEPENDENCIES }}
    secrets:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

  notify_discord:
    needs: [prepare, publish_modrinth]
    uses: Matthiesen-dev/automation/.github/workflows/publish-discord-release.yml@main
    with:
      mod_name: ${{ env.MOD_NAME }}
      version: ${{ needs.prepare.outputs.version }}
      changelog: ${{ github.event.release.body }}
      modrinth_game_version: ${{ env.MODRINTH_GAME_VERSION }}
      modrinth_id: ${{ secrets.MODRINTH_ID }}
      fabric_loader_version: ${{ env.FABRIC_LOADER_VERSION }}
      neoforge_loader_version: ${{ env.NEOFORGE_LOADER_VERSION }}
      discord_icon_url: ${{ env.DISCORD_ICON_URL }}
      github_release_url: ${{ github.event.release.html_url }}
    secrets:
      discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}